engines:
  duplication:
    enabled: true
    exclude_paths:
      - 'test/**'
      - '**/test/**'
exclude_paths:
  - '**.md'
  - '**/examples/**'
  - '**/libecc.js'
  - '**/libecc-post.js'
  - '**/js/dist/*.d.ts'
  - '**/libecc.c'
  - '**/libecc.java'
  - '**/libecc.py'
  - '**/cJSON.*'
