engines:
  duplication:
    enabled: true
    exclude_paths:
      - '**/test/**'
exclude_paths:
  - '**.md'
  - '**/examples/**'
  - '**/libecc.js'
  - '**/libecc-post.js'
  - '**/libopaque.js'
  - '**/libopaque-post.js'
  - '**/liboprf.js'
  - '**/liboprf-post.js'
