name: Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  NDK_VERSION: r25c
  NDK: ${{ PWD }}/android-ndk
  TOOLCHAIN: ${{ NDK }}/toolchains/llvm/prebuilt/linux-x86_64
  API: 24
  AR: ${{ TOOLCHAIN }}/bin/${{ TARGET }}-ar
  AS: ${{ TOOLCHAIN }}/bin/${{ TARGET }}-as
  CC: ${{ TOOLCHAIN }}/bin/${{ TARGET }}${{ env.API }}-clang
  CXX: ${{ TOOLCHAIN }}/bin/${{ TARGET }}${{ env.API }}-clang++
  LD: ${{ TOOLCHAIN }}/bin/${{ TARGET }}-ld
  RANLIB: ${{ TOOLCHAIN }}/bin/${{ TARGET }}-ranlib
  STRIP: ${{ TOOLCHAIN }}/bin/${{ TARGET }}-strip

jobs:

  arm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install packages
        run: |
          sudo apt update
          sudo apt install ninja-build autoconf automake

      - name: setup ndk
        run: |
          wget -nv -O android-ndk.zip https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip
          unzip -qq android-ndk.zip
          mv android-ndk-${NDK_VERSION} android-ndk

      - name: cmake configure
        run: |
          export TARGET=arm-linux-androideabi
          cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=armeabi-v7a \
            -DANDROID_NATIVE_API_LEVEL=$API \
            -DANDROID_STL=c++_static \
            -DCMAKE_BUILD_TYPE=Release -B build -G "Ninja" .

#      - name: c build
#        run: |
#          ./build-c.sh
#          readelf -d build/libecc.so

      - uses: actions/upload-artifact@v3
        with:
          name: ecc-linux-x86_64
          path: |
            build/libecc-jvm.so
          retention-days: 10
