name: c

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install packages
        run: |
          sudo apt update
          sudo apt install ninja-build autoconf automake

      - name: c build
        run: |
          ./build-c.sh
          readelf -d build/libecc.so

      - name: c tests
        run: |
          cd build
          ctest -C "Release" --rerun-failed --output-on-failure
          cd ..

      - name: jvm tests
        run: |
          readelf -d bindings/jvm/libecc-jvm.so
          cd bindings/jvm
          ./gradlew test
          cd ../..

      - uses: actions/upload-artifact@v2
        with:
          name: ecc-linux
          path: |
            build/libecc.so
            build/libecc-jvm.so
          retention-days: 5
