name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install packages
        run: |
          sudo apt update
          sudo apt install ninja-build npm
      - name: install nodejs
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: c build
        run: ./build-c.sh
      - name: c tests
        run: |
          cd build
          ctest -C "Release"
          cd ..
#
#      - name: js tests
#        run: |
#          ./build-wasm.sh
#          cd js/hash
#          npm install
#          npm test
