name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  x86_64-cmake:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install packages
        run: |
          sudo apt update
          sudo apt install ninja-build npm
      - name: install nodejs
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: c tests
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -B build -G "Ninja" .
          cmake --build build --config Release --parallel 2
          ctest --build-and-test build -C "Release"

      - name: js tests
        run: |
          ./build-wasm.sh
          cd js/hash
          npm install
          npm test
