name: javascript

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:

  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install packages
        run: |
          sudo apt update
          sudo apt install ninja-build autoconf automake npm
      - name: install nodejs
        run: |
          sudo npm install -g n
          sudo n 18.14.1
          node --version
      - name: install emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          ./emsdk/emsdk install latest
          ./emsdk/emsdk activate latest

      - name: js build
        run: |
          source ./emsdk/emsdk_env.sh
          ./build-js.sh

      - name: js tests
        run: |
          cd bindings/js
          npm install
          npm test
          cd ../..
