name: js

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install packages
        run: |
          sudo apt update
          sudo apt install ninja-build npm
      - name: install nodejs
        run: |
          sudo npm install -g n
          sudo n 16.3.0
          node --version
      - name: install emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          ./emsdk/emsdk install latest
          ./emsdk/emsdk activate latest

      - name: js build
        run: |
          source ./emsdk/emsdk_env.sh
          ./build-js.sh
      - name: js tests
        run: |
          cd js/ecc
          npm install
          npm test
          cd ../oprf
          npm install
          npm test
          cd ../opaque
          npm install
          npm test
          cd ../..
