name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  x86_64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install packages
        run: |
          sudo apt update
          sudo apt install ninja-build autoconf automake
          sudo apt install python3-pip
          pip3 install --upgrade build
          pip3 install cffi

      - name: c build
        run: |
          ./build-c.sh
          readelf -d build/libecc.so

      - name: c tests
        run: |
          cd build
          ctest -C "Release" --rerun-failed --output-on-failure
          cd ..

      - name: jvm tests
        run: |
          readelf -d bindings/jvm/libecc-jvm.so
          cd bindings/jvm
          ./gradlew test
          cd ../..

      - name: python wheel
        run: |
          cd bindings/python
          python3 cffi_build.py
          python3 -m build --wheel
          cd ../..

      - name: python tests
        run: |
          cd bindings/python
          python3 -m unittest
          cd ../..

      - uses: actions/upload-artifact@v2
        with:
          name: ecc-linux
          path: |
            build/libecc.so
            build/libecc-jvm.so
            bindings/python/src/libecc/_libecc_cffi.*.so
          retention-days: 5
